## 1. 加载数据

```{julia}
includet("../src/main_makie.jl")
# includet("src/zarr.jl")

using Ipaper
using YAXArrays
using Zarr
using ArchGDAL

f = "OUTPUT/global_param_lambda_cv/lambda_cv_2018-2022.zarr" |> path_mnt
ds = open_dataset(f)

grids = names(ds) |> sort
z = ds["grid.2_4"].data
# z = ds[3].data
b = Terra.bbox(z.attrs["bbox"]...)
lon, lat = bbox2dims(b; cellsize=1/240)
lon = collect(lon)
lat = collect(lat)

cellx, celly = bbox2cellsize(b, size(z))
time = 1:229
@time lambda = z[:, :, 1];
lambda[lambda.==0] .= NaN;
```

```{julia}
fact = 10
@time ra = st_resample(zs; fact);
GC.gc()

band = Rasters.Band(["lambda", "ymin", "ymax", "wc"])
dims = ra.dims[1:2]..., band
r = Raster(ra.data, dims; missingval=0f0); # 数据类型要一致

write("lambda_24.tif", r2, force=true)
plot(r[:, :, 1]; colorrange=[0.01, 50])
```

## 2. 然后转到ggplot2进行绘图

```{r}
library(Ipaper)
library(terra)
library(tidyterra)
# pak::pkg_install("tidyterra")
# install.packages("tidyterra")
```

```{r}
r = rast("./OUTPUT/global_param_D24_lambda_cv_2018-2022.tif")
# plot(r)
```

```{r}
write_fig({
  plot(r)
}, 'Figure1.pdf', 10, 5, show=F)
```
